/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class generator_RatingGenerator */

#ifndef _Included_generator_RatingGenerator
#define _Included_generator_RatingGenerator
#ifdef __cplusplus
extern "C" {
#endif
#undef generator_RatingGenerator_ITEMS
#define generator_RatingGenerator_ITEMS 5000L
#undef generator_RatingGenerator_MIN
#define generator_RatingGenerator_MIN 1L
#undef generator_RatingGenerator_MAX
#define generator_RatingGenerator_MAX 5L
/*
 * Class:     generator_RatingGenerator
 * Method:    generateGraph
 * Signature: (Ljava/lang/String;IIDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_generator_RatingGenerator_generateGraph
  (JNIEnv *, jclass, jstring, jint, jint, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
